# This workflow will upload a Python Package using Twine when a release is created

name: Upload Python Package to Test PyPI and Main PyPI

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  job_test:
    name: Upload Python Package to Test PyPI
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
   
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
  job_main:
    name: Upload Python Package to Main PyPI
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
   
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.MAIN_PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/


