# This workflow will upload a Python Package using Twine when a release is created

name: Upload Python Package to Test PyPI

on:
  merge:
    branches:
    - 'main'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.MAIN_PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
